/**
 * ISO 3166-1 alpha-2 countries with international dial codes.
 * Used by CountrySelect and PhoneField across user modals and forms.
 */

export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', dial: '+93', flag: 'af' },
  { code: 'AL', name: 'Albania', dial: '+355', flag: 'al' },
  { code: 'DZ', name: 'Algeria', dial: '+213', flag: 'dz' },
  { code: 'AR', name: 'Argentina', dial: '+54', flag: 'ar' },
  { code: 'AU', name: 'Australia', dial: '+61', flag: 'au' },
  { code: 'AT', name: 'Austria', dial: '+43', flag: 'at' },
  { code: 'BH', name: 'Bahrain', dial: '+973', flag: 'bh' },
  { code: 'BD', name: 'Bangladesh', dial: '+880', flag: 'bd' },
  { code: 'BE', name: 'Belgium', dial: '+32', flag: 'be' },
  { code: 'BR', name: 'Brazil', dial: '+55', flag: 'br' },
  { code: 'BG', name: 'Bulgaria', dial: '+359', flag: 'bg' },
  { code: 'CA', name: 'Canada', dial: '+1', flag: 'ca' },
  { code: 'CL', name: 'Chile', dial: '+56', flag: 'cl' },
  { code: 'CN', name: 'China', dial: '+86', flag: 'cn' },
  { code: 'CO', name: 'Colombia', dial: '+57', flag: 'co' },
  { code: 'HR', name: 'Croatia', dial: '+385', flag: 'hr' },
  { code: 'CY', name: 'Cyprus', dial: '+357', flag: 'cy' },
  { code: 'CZ', name: 'Czech Republic', dial: '+420', flag: 'cz' },
  { code: 'DK', name: 'Denmark', dial: '+45', flag: 'dk' },
  { code: 'EG', name: 'Egypt', dial: '+20', flag: 'eg' },
  { code: 'EE', name: 'Estonia', dial: '+372', flag: 'ee' },
  { code: 'FI', name: 'Finland', dial: '+358', flag: 'fi' },
  { code: 'FR', name: 'France', dial: '+33', flag: 'fr' },
  { code: 'DE', name: 'Germany', dial: '+49', flag: 'de' },
  { code: 'GH', name: 'Ghana', dial: '+233', flag: 'gh' },
  { code: 'GR', name: 'Greece', dial: '+30', flag: 'gr' },
  { code: 'HK', name: 'Hong Kong', dial: '+852', flag: 'hk' },
  { code: 'HU', name: 'Hungary', dial: '+36', flag: 'hu' },
  { code: 'IS', name: 'Iceland', dial: '+354', flag: 'is' },
  { code: 'IN', name: 'India', dial: '+91', flag: 'in' },
  { code: 'ID', name: 'Indonesia', dial: '+62', flag: 'id' },
  { code: 'IE', name: 'Ireland', dial: '+353', flag: 'ie' },
  { code: 'IL', name: 'Israel', dial: '+972', flag: 'il' },
  { code: 'IT', name: 'Italy', dial: '+39', flag: 'it' },
  { code: 'JP', name: 'Japan', dial: '+81', flag: 'jp' },
  { code: 'JO', name: 'Jordan', dial: '+962', flag: 'jo' },
  { code: 'KE', name: 'Kenya', dial: '+254', flag: 'ke' },
  { code: 'KW', name: 'Kuwait', dial: '+965', flag: 'kw' },
  { code: 'LV', name: 'Latvia', dial: '+371', flag: 'lv' },
  { code: 'LB', name: 'Lebanon', dial: '+961', flag: 'lb' },
  { code: 'LT', name: 'Lithuania', dial: '+370', flag: 'lt' },
  { code: 'LU', name: 'Luxembourg', dial: '+352', flag: 'lu' },
  { code: 'MY', name: 'Malaysia', dial: '+60', flag: 'my' },
  { code: 'MX', name: 'Mexico', dial: '+52', flag: 'mx' },
  { code: 'MA', name: 'Morocco', dial: '+212', flag: 'ma' },
  { code: 'NL', name: 'Netherlands', dial: '+31', flag: 'nl' },
  { code: 'NZ', name: 'New Zealand', dial: '+64', flag: 'nz' },
  { code: 'NG', name: 'Nigeria', dial: '+234', flag: 'ng' },
  { code: 'NO', name: 'Norway', dial: '+47', flag: 'no' },
  { code: 'OM', name: 'Oman', dial: '+968', flag: 'om' },
  { code: 'PK', name: 'Pakistan', dial: '+92', flag: 'pk' },
  { code: 'PH', name: 'Philippines', dial: '+63', flag: 'ph' },
  { code: 'PL', name: 'Poland', dial: '+48', flag: 'pl' },
  { code: 'PT', name: 'Portugal', dial: '+351', flag: 'pt' },
  { code: 'QA', name: 'Qatar', dial: '+974', flag: 'qa' },
  { code: 'RO', name: 'Romania', dial: '+40', flag: 'ro' },
  { code: 'RU', name: 'Russia', dial: '+7', flag: 'ru' },
  { code: 'SA', name: 'Saudi Arabia', dial: '+966', flag: 'sa' },
  { code: 'RS', name: 'Serbia', dial: '+381', flag: 'rs' },
  { code: 'SG', name: 'Singapore', dial: '+65', flag: 'sg' },
  { code: 'SK', name: 'Slovakia', dial: '+421', flag: 'sk' },
  { code: 'SI', name: 'Slovenia', dial: '+386', flag: 'si' },
  { code: 'ZA', name: 'South Africa', dial: '+27', flag: 'za' },
  { code: 'KR', name: 'South Korea', dial: '+82', flag: 'kr' },
  { code: 'ES', name: 'Spain', dial: '+34', flag: 'es' },
  { code: 'SE', name: 'Sweden', dial: '+46', flag: 'se' },
  { code: 'CH', name: 'Switzerland', dial: '+41', flag: 'ch' },
  { code: 'TW', name: 'Taiwan', dial: '+886', flag: 'tw' },
  { code: 'TH', name: 'Thailand', dial: '+66', flag: 'th' },
  { code: 'TR', name: 'Turkey', dial: '+90', flag: 'tr' },
  { code: 'UA', name: 'Ukraine', dial: '+380', flag: 'ua' },
  { code: 'AE', name: 'United Arab Emirates', dial: '+971', flag: 'ae' },
  { code: 'GB', name: 'United Kingdom', dial: '+44', flag: 'gb' },
  { code: 'US', name: 'United States', dial: '+1', flag: 'us' },
  { code: 'VN', name: 'Vietnam', dial: '+84', flag: 'vn' },
];

export const countryByCode = (code) =>
  COUNTRIES.find((c) => c.code === code) || null;

export const flagUrl = (flagCode, size = 40) =>
  `https://flagcdn.com/w${size}/${flagCode}.png`;
