/**
 * State / province / region data for countries that have well-defined
 * administrative subdivisions.  Used by StateSelect to show a searchable
 * dropdown instead of a free-text input when the billing / shipping country
 * is one of these.
 *
 * Format: { [ISO-2 country code]: Array<{ code: string, name: string }> }
 * `code` = the subdivision's abbreviation; `name` = display name (stored value).
 */

const STATES = {
  US: [
    { code: 'AL', name: 'Alabama' },
    { code: 'AK', name: 'Alaska' },
    { code: 'AZ', name: 'Arizona' },
    { code: 'AR', name: 'Arkansas' },
    { code: 'CA', name: 'California' },
    { code: 'CO', name: 'Colorado' },
    { code: 'CT', name: 'Connecticut' },
    { code: 'DE', name: 'Delaware' },
    { code: 'FL', name: 'Florida' },
    { code: 'GA', name: 'Georgia' },
    { code: 'HI', name: 'Hawaii' },
    { code: 'ID', name: 'Idaho' },
    { code: 'IL', name: 'Illinois' },
    { code: 'IN', name: 'Indiana' },
    { code: 'IA', name: 'Iowa' },
    { code: 'KS', name: 'Kansas' },
    { code: 'KY', name: 'Kentucky' },
    { code: 'LA', name: 'Louisiana' },
    { code: 'ME', name: 'Maine' },
    { code: 'MD', name: 'Maryland' },
    { code: 'MA', name: 'Massachusetts' },
    { code: 'MI', name: 'Michigan' },
    { code: 'MN', name: 'Minnesota' },
    { code: 'MS', name: 'Mississippi' },
    { code: 'MO', name: 'Missouri' },
    { code: 'MT', name: 'Montana' },
    { code: 'NE', name: 'Nebraska' },
    { code: 'NV', name: 'Nevada' },
    { code: 'NH', name: 'New Hampshire' },
    { code: 'NJ', name: 'New Jersey' },
    { code: 'NM', name: 'New Mexico' },
    { code: 'NY', name: 'New York' },
    { code: 'NC', name: 'North Carolina' },
    { code: 'ND', name: 'North Dakota' },
    { code: 'OH', name: 'Ohio' },
    { code: 'OK', name: 'Oklahoma' },
    { code: 'OR', name: 'Oregon' },
    { code: 'PA', name: 'Pennsylvania' },
    { code: 'RI', name: 'Rhode Island' },
    { code: 'SC', name: 'South Carolina' },
    { code: 'SD', name: 'South Dakota' },
    { code: 'TN', name: 'Tennessee' },
    { code: 'TX', name: 'Texas' },
    { code: 'UT', name: 'Utah' },
    { code: 'VT', name: 'Vermont' },
    { code: 'VA', name: 'Virginia' },
    { code: 'WA', name: 'Washington' },
    { code: 'DC', name: 'Washington D.C.' },
    { code: 'WV', name: 'West Virginia' },
    { code: 'WI', name: 'Wisconsin' },
    { code: 'WY', name: 'Wyoming' },
  ],

  CA: [
    { code: 'AB', name: 'Alberta' },
    { code: 'BC', name: 'British Columbia' },
    { code: 'MB', name: 'Manitoba' },
    { code: 'NB', name: 'New Brunswick' },
    { code: 'NL', name: 'Newfoundland and Labrador' },
    { code: 'NS', name: 'Nova Scotia' },
    { code: 'NT', name: 'Northwest Territories' },
    { code: 'NU', name: 'Nunavut' },
    { code: 'ON', name: 'Ontario' },
    { code: 'PE', name: 'Prince Edward Island' },
    { code: 'QC', name: 'Quebec' },
    { code: 'SK', name: 'Saskatchewan' },
    { code: 'YT', name: 'Yukon' },
  ],

  AU: [
    { code: 'ACT', name: 'Australian Capital Territory' },
    { code: 'NSW', name: 'New South Wales' },
    { code: 'NT',  name: 'Northern Territory' },
    { code: 'QLD', name: 'Queensland' },
    { code: 'SA',  name: 'South Australia' },
    { code: 'TAS', name: 'Tasmania' },
    { code: 'VIC', name: 'Victoria' },
    { code: 'WA',  name: 'Western Australia' },
  ],

  MX: [
    { code: 'AGU', name: 'Aguascalientes' },
    { code: 'BCN', name: 'Baja California' },
    { code: 'BCS', name: 'Baja California Sur' },
    { code: 'CAM', name: 'Campeche' },
    { code: 'CHP', name: 'Chiapas' },
    { code: 'CHH', name: 'Chihuahua' },
    { code: 'CMX', name: 'Ciudad de México' },
    { code: 'COA', name: 'Coahuila' },
    { code: 'COL', name: 'Colima' },
    { code: 'DUR', name: 'Durango' },
    { code: 'GUA', name: 'Guanajuato' },
    { code: 'GRO', name: 'Guerrero' },
    { code: 'HID', name: 'Hidalgo' },
    { code: 'JAL', name: 'Jalisco' },
    { code: 'MEX', name: 'Estado de México' },
    { code: 'MIC', name: 'Michoacán' },
    { code: 'MOR', name: 'Morelos' },
    { code: 'NAY', name: 'Nayarit' },
    { code: 'NLE', name: 'Nuevo León' },
    { code: 'OAX', name: 'Oaxaca' },
    { code: 'PUE', name: 'Puebla' },
    { code: 'QUE', name: 'Querétaro' },
    { code: 'ROO', name: 'Quintana Roo' },
    { code: 'SLP', name: 'San Luis Potosí' },
    { code: 'SIN', name: 'Sinaloa' },
    { code: 'SON', name: 'Sonora' },
    { code: 'TAB', name: 'Tabasco' },
    { code: 'TAM', name: 'Tamaulipas' },
    { code: 'TLA', name: 'Tlaxcala' },
    { code: 'VER', name: 'Veracruz' },
    { code: 'YUC', name: 'Yucatán' },
    { code: 'ZAC', name: 'Zacatecas' },
  ],

  BR: [
    { code: 'AC', name: 'Acre' },
    { code: 'AL', name: 'Alagoas' },
    { code: 'AP', name: 'Amapá' },
    { code: 'AM', name: 'Amazonas' },
    { code: 'BA', name: 'Bahia' },
    { code: 'CE', name: 'Ceará' },
    { code: 'DF', name: 'Distrito Federal' },
    { code: 'ES', name: 'Espírito Santo' },
    { code: 'GO', name: 'Goiás' },
    { code: 'MA', name: 'Maranhão' },
    { code: 'MT', name: 'Mato Grosso' },
    { code: 'MS', name: 'Mato Grosso do Sul' },
    { code: 'MG', name: 'Minas Gerais' },
    { code: 'PA', name: 'Pará' },
    { code: 'PB', name: 'Paraíba' },
    { code: 'PR', name: 'Paraná' },
    { code: 'PE', name: 'Pernambuco' },
    { code: 'PI', name: 'Piauí' },
    { code: 'RJ', name: 'Rio de Janeiro' },
    { code: 'RN', name: 'Rio Grande do Norte' },
    { code: 'RS', name: 'Rio Grande do Sul' },
    { code: 'RO', name: 'Rondônia' },
    { code: 'RR', name: 'Roraima' },
    { code: 'SC', name: 'Santa Catarina' },
    { code: 'SP', name: 'São Paulo' },
    { code: 'SE', name: 'Sergipe' },
    { code: 'TO', name: 'Tocantins' },
  ],

  IN: [
    { code: 'AP', name: 'Andhra Pradesh' },
    { code: 'AR', name: 'Arunachal Pradesh' },
    { code: 'AS', name: 'Assam' },
    { code: 'BR', name: 'Bihar' },
    { code: 'CG', name: 'Chhattisgarh' },
    { code: 'GA', name: 'Goa' },
    { code: 'GJ', name: 'Gujarat' },
    { code: 'HR', name: 'Haryana' },
    { code: 'HP', name: 'Himachal Pradesh' },
    { code: 'JH', name: 'Jharkhand' },
    { code: 'KA', name: 'Karnataka' },
    { code: 'KL', name: 'Kerala' },
    { code: 'MP', name: 'Madhya Pradesh' },
    { code: 'MH', name: 'Maharashtra' },
    { code: 'MN', name: 'Manipur' },
    { code: 'ML', name: 'Meghalaya' },
    { code: 'MZ', name: 'Mizoram' },
    { code: 'NL', name: 'Nagaland' },
    { code: 'OD', name: 'Odisha' },
    { code: 'PB', name: 'Punjab' },
    { code: 'RJ', name: 'Rajasthan' },
    { code: 'SK', name: 'Sikkim' },
    { code: 'TN', name: 'Tamil Nadu' },
    { code: 'TG', name: 'Telangana' },
    { code: 'TR', name: 'Tripura' },
    { code: 'UP', name: 'Uttar Pradesh' },
    { code: 'UK', name: 'Uttarakhand' },
    { code: 'WB', name: 'West Bengal' },
    { code: 'DL', name: 'Delhi' },
    { code: 'JK', name: 'Jammu and Kashmir' },
    { code: 'LA', name: 'Ladakh' },
  ],

  GB: [
    { code: 'ENG', name: 'England' },
    { code: 'SCT', name: 'Scotland' },
    { code: 'WLS', name: 'Wales' },
    { code: 'NIR', name: 'Northern Ireland' },
  ],

  DE: [
    { code: 'BB', name: 'Brandenburg' },
    { code: 'BE', name: 'Berlin' },
    { code: 'BW', name: 'Baden-Württemberg' },
    { code: 'BY', name: 'Bavaria' },
    { code: 'HB', name: 'Bremen' },
    { code: 'HE', name: 'Hesse' },
    { code: 'HH', name: 'Hamburg' },
    { code: 'MV', name: 'Mecklenburg-Vorpommern' },
    { code: 'NI', name: 'Lower Saxony' },
    { code: 'NW', name: 'North Rhine-Westphalia' },
    { code: 'RP', name: 'Rhineland-Palatinate' },
    { code: 'SH', name: 'Schleswig-Holstein' },
    { code: 'SL', name: 'Saarland' },
    { code: 'SN', name: 'Saxony' },
    { code: 'ST', name: 'Saxony-Anhalt' },
    { code: 'TH', name: 'Thuringia' },
  ],

  FR: [
    { code: 'ARA', name: 'Auvergne-Rhône-Alpes' },
    { code: 'BFC', name: 'Bourgogne-Franche-Comté' },
    { code: 'BRE', name: 'Brittany' },
    { code: 'CVL', name: 'Centre-Val de Loire' },
    { code: 'GES', name: 'Grand Est' },
    { code: 'HDF', name: 'Hauts-de-France' },
    { code: 'IDF', name: 'Île-de-France' },
    { code: 'NOR', name: 'Normandy' },
    { code: 'NAQ', name: 'Nouvelle-Aquitaine' },
    { code: 'OCC', name: 'Occitanie' },
    { code: 'PDL', name: 'Pays de la Loire' },
    { code: 'PAC', name: "Provence-Alpes-Côte d'Azur" },
    { code: 'COR', name: 'Corsica' },
  ],

  IT: [
    { code: 'ABR', name: 'Abruzzo' },
    { code: 'BAS', name: 'Basilicata' },
    { code: 'CAL', name: 'Calabria' },
    { code: 'CAM', name: 'Campania' },
    { code: 'EMR', name: 'Emilia-Romagna' },
    { code: 'FVG', name: 'Friuli-Venezia Giulia' },
    { code: 'LAZ', name: 'Lazio' },
    { code: 'LIG', name: 'Liguria' },
    { code: 'LOM', name: 'Lombardy' },
    { code: 'MAR', name: 'Marche' },
    { code: 'MOL', name: 'Molise' },
    { code: 'PIE', name: 'Piedmont' },
    { code: 'PUG', name: 'Apulia' },
    { code: 'SAR', name: 'Sardinia' },
    { code: 'SIC', name: 'Sicily' },
    { code: 'TOS', name: 'Tuscany' },
    { code: 'TAA', name: 'Trentino-Alto Adige' },
    { code: 'UMB', name: 'Umbria' },
    { code: 'VDA', name: "Valle d'Aosta" },
    { code: 'VEN', name: 'Veneto' },
  ],

  ES: [
    { code: 'AN', name: 'Andalusia' },
    { code: 'AR', name: 'Aragon' },
    { code: 'AS', name: 'Asturias' },
    { code: 'CB', name: 'Cantabria' },
    { code: 'CL', name: 'Castile and León' },
    { code: 'CM', name: 'Castilla-La Mancha' },
    { code: 'CT', name: 'Catalonia' },
    { code: 'EX', name: 'Extremadura' },
    { code: 'GA', name: 'Galicia' },
    { code: 'IB', name: 'Balearic Islands' },
    { code: 'IC', name: 'Canary Islands' },
    { code: 'LA', name: 'La Rioja' },
    { code: 'MD', name: 'Community of Madrid' },
    { code: 'MC', name: 'Murcia' },
    { code: 'NC', name: 'Navarre' },
    { code: 'PV', name: 'Basque Country' },
    { code: 'VC', name: 'Valencian Community' },
  ],

  AE: [
    { code: 'AZ', name: 'Abu Dhabi' },
    { code: 'AJ', name: 'Ajman' },
    { code: 'DU', name: 'Dubai' },
    { code: 'FU', name: 'Fujairah' },
    { code: 'RK', name: 'Ras al-Khaimah' },
    { code: 'SH', name: 'Sharjah' },
    { code: 'UQ', name: 'Umm al-Quwain' },
  ],

  SA: [
    { code: 'RI',  name: 'Riyadh' },
    { code: 'MK',  name: 'Makkah' },
    { code: 'MD',  name: 'Madinah' },
    { code: 'QA',  name: 'Al-Qassim' },
    { code: 'EP',  name: 'Eastern Province' },
    { code: 'AS',  name: 'Asir' },
    { code: 'TB',  name: 'Tabuk' },
    { code: 'HA',  name: 'Hail' },
    { code: 'NB',  name: 'Northern Borders' },
    { code: 'JZ',  name: 'Jizan' },
    { code: 'NJ',  name: 'Najran' },
    { code: 'AL',  name: 'Al Bahah' },
    { code: 'JF',  name: 'Al Jawf' },
  ],

  CN: [
    { code: 'AH', name: 'Anhui' },
    { code: 'BJ', name: 'Beijing' },
    { code: 'CQ', name: 'Chongqing' },
    { code: 'FJ', name: 'Fujian' },
    { code: 'GS', name: 'Gansu' },
    { code: 'GD', name: 'Guangdong' },
    { code: 'GX', name: 'Guangxi' },
    { code: 'GZ', name: 'Guizhou' },
    { code: 'HI', name: 'Hainan' },
    { code: 'HE', name: 'Hebei' },
    { code: 'HL', name: 'Heilongjiang' },
    { code: 'HA', name: 'Henan' },
    { code: 'HB', name: 'Hubei' },
    { code: 'HN', name: 'Hunan' },
    { code: 'NM', name: 'Inner Mongolia' },
    { code: 'JS', name: 'Jiangsu' },
    { code: 'JX', name: 'Jiangxi' },
    { code: 'JL', name: 'Jilin' },
    { code: 'LN', name: 'Liaoning' },
    { code: 'NX', name: 'Ningxia' },
    { code: 'QH', name: 'Qinghai' },
    { code: 'SN', name: 'Shaanxi' },
    { code: 'SD', name: 'Shandong' },
    { code: 'SH', name: 'Shanghai' },
    { code: 'SX', name: 'Shanxi' },
    { code: 'SC', name: 'Sichuan' },
    { code: 'TJ', name: 'Tianjin' },
    { code: 'XJ', name: 'Xinjiang' },
    { code: 'XZ', name: 'Tibet' },
    { code: 'YN', name: 'Yunnan' },
    { code: 'ZJ', name: 'Zhejiang' },
  ],

  JP: [
    { code: 'AI', name: 'Aichi' },         { code: 'AK', name: 'Akita' },
    { code: 'AO', name: 'Aomori' },        { code: 'CH', name: 'Chiba' },
    { code: 'EH', name: 'Ehime' },         { code: 'FK', name: 'Fukui' },
    { code: 'FO', name: 'Fukuoka' },       { code: 'FS', name: 'Fukushima' },
    { code: 'GF', name: 'Gifu' },          { code: 'GN', name: 'Gunma' },
    { code: 'HR', name: 'Hiroshima' },     { code: 'HK', name: 'Hokkaido' },
    { code: 'HG', name: 'Hyogo' },         { code: 'IB', name: 'Ibaraki' },
    { code: 'IS', name: 'Ishikawa' },      { code: 'IW', name: 'Iwate' },
    { code: 'KG', name: 'Kagawa' },        { code: 'KS', name: 'Kagoshima' },
    { code: 'KN', name: 'Kanagawa' },      { code: 'KC', name: 'Kochi' },
    { code: 'KM', name: 'Kumamoto' },      { code: 'KT', name: 'Kyoto' },
    { code: 'ME', name: 'Mie' },           { code: 'MY', name: 'Miyagi' },
    { code: 'MZ', name: 'Miyazaki' },      { code: 'NG', name: 'Nagano' },
    { code: 'NS', name: 'Nagasaki' },      { code: 'NR', name: 'Nara' },
    { code: 'NT', name: 'Niigata' },       { code: 'OT', name: 'Oita' },
    { code: 'OK', name: 'Okayama' },       { code: 'OW', name: 'Okinawa' },
    { code: 'OS', name: 'Osaka' },         { code: 'SG', name: 'Saga' },
    { code: 'ST', name: 'Saitama' },       { code: 'SH', name: 'Shiga' },
    { code: 'SM', name: 'Shimane' },       { code: 'SZ', name: 'Shizuoka' },
    { code: 'TC', name: 'Tochigi' },       { code: 'TK', name: 'Tokushima' },
    { code: 'TO', name: 'Tokyo' },         { code: 'TR', name: 'Tottori' },
    { code: 'TY', name: 'Toyama' },        { code: 'WK', name: 'Wakayama' },
    { code: 'YM', name: 'Yamagata' },      { code: 'YG', name: 'Yamaguchi' },
    { code: 'YN', name: 'Yamanashi' },
  ],

  ZA: [
    { code: 'EC',  name: 'Eastern Cape' },
    { code: 'FS',  name: 'Free State' },
    { code: 'GT',  name: 'Gauteng' },
    { code: 'LP',  name: 'Limpopo' },
    { code: 'MP',  name: 'Mpumalanga' },
    { code: 'NC',  name: 'Northern Cape' },
    { code: 'NW',  name: 'North West' },
    { code: 'WC',  name: 'Western Cape' },
    { code: 'ZN',  name: 'KwaZulu-Natal' },
  ],

  NG: [
    { code: 'AB', name: 'Abia' },          { code: 'AD', name: 'Adamawa' },
    { code: 'AK', name: 'Akwa Ibom' },     { code: 'AN', name: 'Anambra' },
    { code: 'BA', name: 'Bauchi' },        { code: 'BY', name: 'Bayelsa' },
    { code: 'BE', name: 'Benue' },         { code: 'BO', name: 'Borno' },
    { code: 'CR', name: 'Cross River' },   { code: 'DE', name: 'Delta' },
    { code: 'EB', name: 'Ebonyi' },        { code: 'ED', name: 'Edo' },
    { code: 'EK', name: 'Ekiti' },         { code: 'EN', name: 'Enugu' },
    { code: 'FC', name: 'FCT (Abuja)' },   { code: 'GO', name: 'Gombe' },
    { code: 'IM', name: 'Imo' },           { code: 'JI', name: 'Jigawa' },
    { code: 'KD', name: 'Kaduna' },        { code: 'KN', name: 'Kano' },
    { code: 'KB', name: 'Katsina' },       { code: 'KE', name: 'Kebbi' },
    { code: 'KO', name: 'Kogi' },          { code: 'KW', name: 'Kwara' },
    { code: 'LA', name: 'Lagos' },         { code: 'NA', name: 'Nasarawa' },
    { code: 'NI', name: 'Niger' },         { code: 'OG', name: 'Ogun' },
    { code: 'ON', name: 'Ondo' },          { code: 'OS', name: 'Osun' },
    { code: 'OY', name: 'Oyo' },           { code: 'PL', name: 'Plateau' },
    { code: 'RI', name: 'Rivers' },        { code: 'SO', name: 'Sokoto' },
    { code: 'TA', name: 'Taraba' },        { code: 'YO', name: 'Yobe' },
    { code: 'ZA', name: 'Zamfara' },
  ],

  AR: [
    { code: 'B', name: 'Buenos Aires Province' },
    { code: 'C', name: 'Buenos Aires City' },
    { code: 'K', name: 'Catamarca' },
    { code: 'H', name: 'Chaco' },
    { code: 'U', name: 'Chubut' },
    { code: 'X', name: 'Córdoba' },
    { code: 'W', name: 'Corrientes' },
    { code: 'E', name: 'Entre Ríos' },
    { code: 'P', name: 'Formosa' },
    { code: 'Y', name: 'Jujuy' },
    { code: 'L', name: 'La Pampa' },
    { code: 'F', name: 'La Rioja' },
    { code: 'M', name: 'Mendoza' },
    { code: 'N', name: 'Misiones' },
    { code: 'Q', name: 'Neuquén' },
    { code: 'R', name: 'Río Negro' },
    { code: 'A', name: 'Salta' },
    { code: 'J', name: 'San Juan' },
    { code: 'D', name: 'San Luis' },
    { code: 'Z', name: 'Santa Cruz' },
    { code: 'S', name: 'Santa Fe' },
    { code: 'G', name: 'Santiago del Estero' },
    { code: 'V', name: 'Tierra del Fuego' },
    { code: 'T', name: 'Tucumán' },
  ],

  CO: [
    { code: 'AMA', name: 'Amazonas' },     { code: 'ANT', name: 'Antioquia' },
    { code: 'ARA', name: 'Arauca' },       { code: 'ATL', name: 'Atlántico' },
    { code: 'BOL', name: 'Bolívar' },      { code: 'BOY', name: 'Boyacá' },
    { code: 'CAL', name: 'Caldas' },       { code: 'CAQ', name: 'Caquetá' },
    { code: 'CAS', name: 'Casanare' },     { code: 'CAU', name: 'Cauca' },
    { code: 'CES', name: 'Cesar' },        { code: 'CHO', name: 'Chocó' },
    { code: 'COR', name: 'Córdoba' },      { code: 'CUN', name: 'Cundinamarca' },
    { code: 'DC',  name: 'Bogotá D.C.' },  { code: 'GUA', name: 'Guainía' },
    { code: 'GUV', name: 'Guaviare' },     { code: 'HUI', name: 'Huila' },
    { code: 'LAG', name: 'La Guajira' },   { code: 'MAG', name: 'Magdalena' },
    { code: 'MET', name: 'Meta' },         { code: 'NAR', name: 'Nariño' },
    { code: 'NSA', name: 'Norte de Santander' },
    { code: 'PUT', name: 'Putumayo' },     { code: 'QUI', name: 'Quindío' },
    { code: 'RIS', name: 'Risaralda' },    { code: 'SAN', name: 'Santander' },
    { code: 'SAP', name: 'San Andrés y Providencia' },
    { code: 'SUC', name: 'Sucre' },        { code: 'TOL', name: 'Tolima' },
    { code: 'VAC', name: 'Valle del Cauca' },
    { code: 'VAU', name: 'Vaupés' },       { code: 'VID', name: 'Vichada' },
  ],

  RU: [
    { code: 'AD',  name: 'Adygea' },           { code: 'AL',  name: 'Altai Republic' },
    { code: 'BA',  name: 'Bashkortostan' },     { code: 'BU',  name: 'Buryatia' },
    { code: 'CE',  name: 'Chechnya' },          { code: 'CU',  name: 'Chuvashia' },
    { code: 'DA',  name: 'Dagestan' },          { code: 'IN',  name: 'Ingushetia' },
    { code: 'KB',  name: 'Kabardino-Balkaria' },{ code: 'KL',  name: 'Kalmykia' },
    { code: 'KC',  name: 'Karachay-Cherkessia' },
    { code: 'KR',  name: 'Karelia' },           { code: 'KK',  name: 'Khakassia' },
    { code: 'KO',  name: 'Komi' },              { code: 'ME',  name: 'Mari El' },
    { code: 'MO',  name: 'Mordovia' },          { code: 'SA',  name: 'Sakha (Yakutia)' },
    { code: 'SE',  name: 'North Ossetia' },     { code: 'TA',  name: 'Tatarstan' },
    { code: 'TY',  name: 'Tuva' },              { code: 'UD',  name: 'Udmurtia' },
    { code: 'MOS', name: 'Moscow' },            { code: 'SPE', name: 'Saint Petersburg' },
    { code: 'KDA', name: 'Krasnodar Krai' },    { code: 'STA', name: 'Stavropol Krai' },
    { code: 'SVE', name: 'Sverdlovsk Oblast' }, { code: 'NSO', name: 'Novosibirsk Oblast' },
    { code: 'KEM', name: 'Kemerovo Oblast' },   { code: 'IRK', name: 'Irkutsk Oblast' },
    { code: 'KRS', name: 'Krasnoyarsk Krai' },  { code: 'PRI', name: 'Primorsky Krai' },
    { code: 'NVG', name: 'Novgorod Oblast' },   { code: 'PSK', name: 'Pskov Oblast' },
  ],

  TR: [
    { code: 'AD', name: 'Adana' },       { code: 'AK', name: 'Ankara' },
    { code: 'AN', name: 'Antalya' },     { code: 'BU', name: 'Bursa' },
    { code: 'DI', name: 'Diyarbakır' },  { code: 'ER', name: 'Erzurum' },
    { code: 'ES', name: 'Eskişehir' },   { code: 'GA', name: 'Gaziantep' },
    { code: 'IS', name: 'Istanbul' },    { code: 'IZ', name: 'İzmir' },
    { code: 'KO', name: 'Konya' },       { code: 'MR', name: 'Mersin' },
    { code: 'SA', name: 'Samsun' },      { code: 'TR', name: 'Trabzon' },
    { code: 'VN', name: 'Van' },
  ],

  PK: [
    { code: 'BA', name: 'Balochistan' },
    { code: 'GB', name: 'Gilgit-Baltistan' },
    { code: 'IS', name: 'Islamabad Capital Territory' },
    { code: 'AK', name: 'Azad Kashmir' },
    { code: 'KP', name: 'Khyber Pakhtunkhwa' },
    { code: 'PB', name: 'Punjab' },
    { code: 'SD', name: 'Sindh' },
  ],

  NL: [
    { code: 'DR', name: 'Drenthe' },         { code: 'FL', name: 'Flevoland' },
    { code: 'FR', name: 'Friesland' },        { code: 'GE', name: 'Gelderland' },
    { code: 'GR', name: 'Groningen' },        { code: 'LI', name: 'Limburg' },
    { code: 'NB', name: 'North Brabant' },    { code: 'NH', name: 'North Holland' },
    { code: 'OV', name: 'Overijssel' },       { code: 'UT', name: 'Utrecht' },
    { code: 'ZE', name: 'Zeeland' },          { code: 'ZH', name: 'South Holland' },
  ],

  BE: [
    { code: 'VAN', name: 'Antwerp' },         { code: 'BRU', name: 'Brussels' },
    { code: 'VOV', name: 'East Flanders' },   { code: 'VBR', name: 'Flemish Brabant' },
    { code: 'WHT', name: 'Hainaut' },         { code: 'WLG', name: 'Liège' },
    { code: 'VLI', name: 'Limburg' },         { code: 'WLX', name: 'Luxembourg' },
    { code: 'WNA', name: 'Namur' },           { code: 'VOV', name: 'West Flanders' },
    { code: 'VWV', name: 'West Flanders' },   { code: 'WBR', name: 'Walloon Brabant' },
  ],

  CH: [
    { code: 'AG', name: 'Aargau' },           { code: 'AI', name: 'Appenzell Innerrhoden' },
    { code: 'AR', name: 'Appenzell Ausserrhoden' },
    { code: 'BE', name: 'Bern' },             { code: 'BL', name: 'Basel-Landschaft' },
    { code: 'BS', name: 'Basel-Stadt' },       { code: 'FR', name: 'Fribourg' },
    { code: 'GE', name: 'Geneva' },            { code: 'GL', name: 'Glarus' },
    { code: 'GR', name: 'Graubünden' },        { code: 'JU', name: 'Jura' },
    { code: 'LU', name: 'Lucerne' },           { code: 'NE', name: 'Neuchâtel' },
    { code: 'NW', name: 'Nidwalden' },         { code: 'OW', name: 'Obwalden' },
    { code: 'SG', name: 'St. Gallen' },        { code: 'SH', name: 'Schaffhausen' },
    { code: 'SO', name: 'Solothurn' },         { code: 'SZ', name: 'Schwyz' },
    { code: 'TG', name: 'Thurgau' },           { code: 'TI', name: 'Ticino' },
    { code: 'UR', name: 'Uri' },               { code: 'VD', name: 'Vaud' },
    { code: 'VS', name: 'Valais' },            { code: 'ZG', name: 'Zug' },
    { code: 'ZH', name: 'Zurich' },
  ],

  SE: [
    { code: 'AB', name: 'Stockholm County' },  { code: 'AC', name: 'Västerbotten' },
    { code: 'BD', name: 'Norrbotten' },         { code: 'C',  name: 'Uppsala' },
    { code: 'D',  name: 'Södermanland' },       { code: 'E',  name: 'Östergötland' },
    { code: 'F',  name: 'Jönköping' },          { code: 'G',  name: 'Kronoberg' },
    { code: 'H',  name: 'Kalmar' },             { code: 'I',  name: 'Gotland' },
    { code: 'K',  name: 'Blekinge' },           { code: 'M',  name: 'Skåne' },
    { code: 'N',  name: 'Halland' },            { code: 'O',  name: 'Västra Götaland' },
    { code: 'S',  name: 'Värmland' },           { code: 'T',  name: 'Örebro' },
    { code: 'U',  name: 'Västmanland' },        { code: 'W',  name: 'Dalarna' },
    { code: 'X',  name: 'Gävleborg' },          { code: 'Y',  name: 'Västernorrland' },
    { code: 'Z',  name: 'Jämtland' },
  ],

  NO: [
    { code: 'AG', name: 'Agder' },             { code: 'INN', name: 'Innlandet' },
    { code: 'MR',  name: 'Møre og Romsdal' },  { code: 'NOR', name: 'Nordland' },
    { code: 'OSL', name: 'Oslo' },             { code: 'ROG', name: 'Rogaland' },
    { code: 'TR',  name: 'Troms og Finnmark' },{ code: 'TRN', name: 'Trøndelag' },
    { code: 'VES', name: 'Vestfold og Telemark' },
    { code: 'VIK', name: 'Viken' },            { code: 'VST', name: 'Vestland' },
  ],

  DK: [
    { code: 'HS', name: 'Capital Region' },
    { code: 'MJ', name: 'Central Denmark' },
    { code: 'NS', name: 'North Denmark' },
    { code: 'SJ', name: 'Zealand' },
    { code: 'SD', name: 'Southern Denmark' },
  ],

  PL: [
    { code: 'DS', name: 'Lower Silesia' },      { code: 'KP', name: 'Kuyavian-Pomerania' },
    { code: 'LU', name: 'Lublin' },             { code: 'LB', name: 'Lubusz' },
    { code: 'LD', name: 'ódź' },               { code: 'MA', name: 'Lesser Poland' },
    { code: 'MZ', name: 'Masovia' },            { code: 'OP', name: 'Opole' },
    { code: 'PK', name: 'Subcarpathia' },       { code: 'PD', name: 'Podlaskie' },
    { code: 'PM', name: 'Pomerania' },          { code: 'SL', name: 'Silesia' },
    { code: 'SK', name: 'Świętokrzyskie' },     { code: 'WN', name: 'Warmian-Masuria' },
    { code: 'WP', name: 'Greater Poland' },     { code: 'ZP', name: 'West Pomerania' },
  ],
};

export default STATES;

/**
 * Returns the state list for a given country code, or [] if none defined.
 */
export function getStates(countryCode) {
  return STATES[countryCode] || [];
}

/**
 * Returns true if a country has a defined state/province list.
 */
export function hasStates(countryCode) {
  return (STATES[countryCode]?.length || 0) > 0;
}
